import string
profiles,admins,ans,answer,achieve,ask,yn,life,quits=[],[],[],[],[],["1.Expert","2.Friend","3.Magic 8 Ball"],['yes','yeah','y','n','no','nah'],['life','lifeline','lifelie','liflie','lifline','lilfeine','lilefine','line','lie','liefline','lieline'],['quit','quits','qut','qt','leave','leve','lea','exit','exi','ext']
user,password,usercreate,userlogin,high,level,matches,wins,wl,lifeans,avatar,rank,padmin,isadmin='','','','','0','1','0','0','0','','','','',''
xp,levelxp,ll,x,y=0,0,0,1,1
achievement=[["Victor","Win a game."],["Coward Victor","Win using a lifeline."],["Lucky","Win using all lifelines."],["Brave and Bold","Win using no lifeline."],["Shameless","Lose after using all lifelines."],["Professional","Reach level 50."],["Master","Reach level 100."],["Champion","Win 25 games."],["Legend","Win 50 games."],["True Legend","Secret"],["Duped","Get the wrong answer after asking an Expert."],["Betrayed","Get the wrong answer after asking a Friend."],["Fortune Teller","Get the right answer after asking the Magic 8 Ball."],["Overconfident","Enter a different answer after using a lifeline and get it wrong."],["Intuitive","Enter a different answer after using a lifeline and get it right."]]
gamecredits="="*172+"CREDITS".center(172)+"="*172+"\n"+"THE SQUAD GAMES presents".center(172)+"\n\n"+" RJK'S  TRIVIA  QUEST™".center(172)+"\n\n"+"Created by".center(172)+"Rishaan Jacob Kuriakose".center(172)+"\n\n"+"Editing and Testing".center(172)+"Rocky Joseph".center(172)+"\n\n"+"Produced by THE SQUAD GAMES".center(172)+"\n\n"+"Copyright © 2020-2021".center(172)+"All rights go to THE SQUAD™ Games PVT. LTD.".center(172)+"\n\n"+"THANKS FOR PLAYING!".center(172)
patch="="*172+"HELP".center(172)+"="*172+"\n"+"RJKTQ® PATCH 2.2.6.9".center(172)+"\nProfile\nPlayers have to create an account or log into an existing one when the game is run.\nAdmins have to enter the admin clearance key while logging in with / creating an account.\nThe profile lists your level, no. of matches played by you, win-loss ratio, ranking, achievements, items, avatar etc. as a player or displays your admin pos. as an admin.\nThe profile can be displayed whenever you want, from the menu.\n\nRankings\nYou can see your rank in the game by selecting 'Leaderboard' in the menu among others who played the game in the PC.\nRanking will be based on highest scores earned in Quick Play, level and no. of achievements earned.\n\nAchievements\nBy doing a special set of tasks, you can receive achievements that can enhance your profile.\n\nQuick Play\nSelecting 'Play' in the game menu opens a 1-round match which rewards EXP for levelling up.\nThe EXP equals the score you gain.\nThe game is played by answering a set of 20 questions, randomly selected.\nThere are 3 lifelines provided that can be used during each attempt, that provide with probable correct answers to the questions. The lifelines may not give you the right answers all the time.\n\nSettings\nThe admin can manipulate stored data such as data related to questions, answers, leaderboard, buffer texts and accounts.\nThe primary admin (system owner) has access to changing admin clearance key and editing admin activity."
yes,no=yn[0:3],yn[3:6]
userchar=list(string.ascii_lowercase+string.ascii_uppercase+string.digits+"_")
